name: Update Dependencies
on:
  workflow_dispatch:
  schedule:
    - cron: 0 21 * * 5

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    if: ${{ github.repository == 'alextheman231/neurosongs-2' }}
    uses: alextheman231/github-actions/.github/workflows/update-dependencies.yml@f00ea95a57c8d8e9810149d2b5c5dca1af7d8058 # v6.0.0
    secrets:
      GITHUB_ACTIONS_TOKEN: ${{ secrets.ALEX_UP_BOT_GITHUB_TOKEN }}
