name: Update Dependencies
on:
  workflow_dispatch:
  schedule:
    - cron: 0 21 * * 5

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    if: ${{ github.repository == 'alextheman231/neurosongs-2' }}
    uses: alextheman231/github-actions/.github/workflows/update-dependencies.yml@40d4eac5a7058957e6fe46cafe068d92eade73d8 # v7.0.1
    secrets:
      APP_ID: ${{ secrets.ALEX_UP_BOT_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
